name: "Publish Release"

on:
  release:
    types: ["published"]

jobs:
  publish_release:

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v3"
        with:
          dotnet-version: 7.x

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test

      - name: Publish
        run: |
          cd ./NadekoHub
          dotnet publish -c Release -r win-x64 -o ~/build/NadekoHub_win-x64 --self-contained
          dotnet publish -c Release -r win-arm64 -o ~/build/NadekoHub_win-arm64 --self-contained
          dotnet publish -c Release -r linux-x64 -o ~/build/NadekoHub_linux-x64 --self-contained
          dotnet publish -c Release -r linux-arm64 -o ~/build/NadekoHub_linux-arm64 --self-contained
          dotnet publish -c Release -r osx-x64 -o ~/build/NadekoHub_osx-x64 --self-contained
          dotnet publish -c Release -r osx-arm64 -o ~/build/NadekoHub_osx-arm64 --self-contained
          cd ../

      - name: Package
        run: |
          mkdir -p ~/build/zips
          zip -r9 ~/build/zips/NadekoHub_win-x64.zip ~/build/NadekoHub_win-x64/*
          zip -r9 ~/build/zips/NadekoHub_win-arm64.zip ~/build/NadekoHub_win-arm64/*
          zip -r9 ~/build/zips/NadekoHub_linux-x64.zip ~/build/NadekoHub_linux-x64/*
          zip -r9 ~/build/zips/NadekoHub_linux-arm64.zip ~/build/NadekoHub_linux-arm64/*
          zip -r9 ~/build/zips/NadekoHub_osx-x64.zip ~/build/NadekoHub_osx-x64/*
          zip -r9 ~/build/zips/NadekoHub_osx-arm64.zip ~/build/NadekoHub_osx-arm64/*

      - name: "Upload Packages To Github Release"
        uses: "ncipollo/release-action@v1"
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "~/build/zips/*"
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
          omitBodyDuringUpdate: true # We don't want to update the body of the release.
          omitNameDuringUpdate: true # We don't want to update the name of the release.